UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '001';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '002';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '003';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '004';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '005';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '006';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '007';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '008';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '009';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '010';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '011';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '012';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '013';
UPDATE asanas SET category_name_en = 'Standing Twist Pose' WHERE image_number = '014';
UPDATE asanas SET category_name_en = 'Standing Twist Pose' WHERE image_number = '015';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '016';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '017';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '018';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '019';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '020';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '021';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '022';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '023';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '024';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '025';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '026';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '027';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '028';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '029';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '030';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '031';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '032';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '033';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '034';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '035';
UPDATE asanas SET category_name_en = 'Seated Side bend Pose' WHERE image_number = '036';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '037';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '038';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '039';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '040';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '041';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '042';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '043';
UPDATE asanas SET category_name_en = 'Standing Side bend Pose' WHERE image_number = '044';
UPDATE asanas SET category_name_en = 'Standing Side bend Pose' WHERE image_number = '045';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '046';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '047';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '048';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '049';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '050';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '051';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '052';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '053';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '054';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '055';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '056';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '057';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '058';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '059';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '060';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '061';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '062';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '063';
UPDATE asanas SET category_name_en = '' WHERE image_number = '064';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '065';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '066';
UPDATE asanas SET category_name_en = 'Standing Inversion Pose' WHERE image_number = '067';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '068';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '069';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '070';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '071';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '072';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '073';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '074';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '075';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '076';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '077';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '078';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '079';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '080';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '081';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '082';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '083';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '084';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '085';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '086';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '087';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '088';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '089';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '090';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '091';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '092';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '093';
UPDATE asanas SET category_name_en = 'Supine Twist Pose' WHERE image_number = '094';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '095';
UPDATE asanas SET category_name_en = 'Supine Inversion Pose' WHERE image_number = '096';
UPDATE asanas SET category_name_en = '' WHERE image_number = '097';
UPDATE asanas SET category_name_en = '' WHERE image_number = '098';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '099';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '100';
UPDATE asanas SET category_name_en = '' WHERE image_number = '101';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '102';
UPDATE asanas SET category_name_en = '' WHERE image_number = '103';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '104';
UPDATE asanas SET category_name_en = '' WHERE image_number = '105';
UPDATE asanas SET category_name_en = '' WHERE image_number = '106';
UPDATE asanas SET category_name_en = '' WHERE image_number = '107';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '108';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '109';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '110';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '111';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '112';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '113';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '114';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '115';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '116';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '117';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '118';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '119';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '120';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '121';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '122';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '123';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '124';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '125';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '126';
UPDATE asanas SET category_name_en = 'Standing Backbend Pose' WHERE image_number = '127';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '128';
UPDATE asanas SET category_name_en = 'Supine Twist Pose' WHERE image_number = '129';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '130';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '131';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '132';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '133';
UPDATE asanas SET category_name_en = 'Supine Compression Pose' WHERE image_number = '134';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '135';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '136';
UPDATE asanas SET category_name_en = 'Seated Twist Pose' WHERE image_number = '137';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '138';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '139';
UPDATE asanas SET category_name_en = 'Standing Backbend Pose' WHERE image_number = '140';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '141';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '142';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '143';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '144';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '145';
UPDATE asanas SET category_name_en = '' WHERE image_number = '146';
UPDATE asanas SET category_name_en = '' WHERE image_number = '147';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '148';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '149';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '150';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '151';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '152';
UPDATE asanas SET category_name_en = 'Supine Forward bend Pose' WHERE image_number = '153';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '154';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '155';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '156';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '157';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '158';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '159';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '160';
UPDATE asanas SET category_name_en = 'Seated Forward bend Pose' WHERE image_number = '161';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '162';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '163';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '164';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '165';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '166';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '167';
UPDATE asanas SET category_name_en = 'Seated Compression Pose' WHERE image_number = '168';
UPDATE asanas SET category_name_en = 'Standing Compression Pose' WHERE image_number = '169';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '170';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '171';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '172';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '173';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '174';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '175';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '176';
UPDATE asanas SET category_name_en = '' WHERE image_number = '177';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '178';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '179';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '180';
UPDATE asanas SET category_name_en = 'Seated Backbend Pose' WHERE image_number = '181';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '182';
UPDATE asanas SET category_name_en = 'Standing Forward bend Pose' WHERE image_number = '183';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '184';
UPDATE asanas SET category_name_en = 'Supine Backbend Pose' WHERE image_number = '185';